# -*- coding: utf-8 -*-

project = u''
copyright = u'2019, Space Applications Services'
author = u'Yamcs Team'

from xml.etree import ElementTree as ET

ET.register_namespace('', 'http://maven.apache.org/POM/4.0.0')
tree = ET.ElementTree()
tree.parse('../pom.xml')
p = tree.getroot().find('{http://maven.apache.org/POM/4.0.0}version')

# The short X.Y version
version = p.text

# The full version, including alpha/beta/rc tags
release = version

extensions = [
    'sphinxcontrib.fulltoc',
]

# Add any paths that contain templates here, relative to this directory.
#templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = [u'_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'nature'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'sidebarwidth': '300px',
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#html_static_path = ['_static']

html_show_sourcelink = False
